all:
	@echo "Compiling..."
	javac-algs4 Run.java
run:
test:
	@echo "Testing..."
	javac-algs4 WordNet.java
	# java-algs4 WordNet ../test/wordnet/synsets100-subgraph.txt ../test/wordnet/hypernyms100-subgraph.txt
	java-algs4 WordNet ../test/wordnet/synsets.txt ../test/wordnet/hypernyms.txt
clean:
	@echo "Clean up..."
	rm -rf *.class
