all:
	@echo "Compiling..."
	javac-algs4 Run.java
run:
test:
	@echo "Testing..."
	# javac-algs4 WordNet.java
	# java-algs4 WordNet ../test/wordnet/synsets.txt ../test/wordnet/hypernyms.txt
	javac-algs4 SAP.java
	java-algs4 SAP ../test/wordnet/digraph3.txt
clean:
	@echo "Clean up..."
	rm -rf *.class
